before_script: 
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq
 - sudo apt-get install -y --force-yes gcc-arm-none-eabi

script: make

# whitelist
branches:
  only:
    - release/vertigo-1

after_success:
  - mkdir -p releases
  - cp LPC1768/main.bin releases/firmware-$TRAVIS_COMMIT.bin
  
deploy:
  provider: s3
  access_key_id:
    secure: "X2Dv8kZNdjmrTBohNuS0HKFEbiY6cg407sbCTR2hQoJVt98+qEi0mLevO+MoNXSgDdQS8fUkd3H1/KG8lrVtqitxZDhZQJ/sHr4Rzu5Tyx99lmRoU27ELNzR8NR2hdJXTmUYtnWiyu/13UDcnnULI/Y4NBETOl9EjE7JEHfdOEyB6ynmt/C9vM7Q6mErZTJL3WFuXh+22dgn0SBKRK1VkX71+GZ8CTho4iQNxpg7jwzF4lSZVXQ0j8sa0x2rhidpRuTwTB4OsNRr3Y/WI2GvClbSZ7Rewc27x8KD7Y4W/wCmb/kQ5C+N5AVhhRsZXXmDjVrzF1ZNR+Fix971cPHMbbe1hZ6yQcL6kPNKJX+OpVFOsk2R8BoPUUtvL4SqR1fpQLVg1bb2so3fL4FluAxVvS6TGwcEJ9RbBfHMHAFEwwlefYKQ7SN6LBRAkWtXsU7+531URbk9KfQ+9MfjRjcZg+h1Uz27rX0jhwf/lYp7Da1rfpCNtsr/IXthJUiEeRZyEyq5Jkb6VaQ1IRi1DNFsaesrDXY+ElJ/vG+o8pA7CLpO0Ys+zGzmhJJgRcmtGSA4NJXmigjbF1CFyc8jm+mddD778+ulRHwWm7UNwufeJefykDj37/w9wVCHXs+EY5X24RCJK2QS1BodbHMZt4oivqR/c0HgME0aV7veP7I9IAI="
  secret_access_key:
    secure: "dtupqffrxrUvdsYvPO06Er6OZ9LSan4GIDEp4LxJqsmf+uiT+uJ45+dn/Q1vHuHT+bgwgWfnT8IdCYNNpoVnMPAOptOaoxlfpl1FA9lqi6ltQ55dGEdZX0tXdhcJ8W1Ek8UVSZIkzsJAt4EfpoJxKmo+dYtMqq46JS5odEUwrPEmJ2NVh/48cbEsIGqqGW2gdHQ2njUbLvJibQaNC+az32bDunQJvlU2aWvSna8lyihG0hRtDJxNZaD9GeG+Fg+RUYnlD6x0AaxNNR+HkyQrxBAb9FmmpHXP0s30FZ2OBk+Gq0wjxYnNXaRkor4NZSpiZqKJ1GwNi47HmW/dy2Xu7SpAauMGaXhnCCZ2jFrGvxD+JEEGu1QS+BLHHRWRrUPbdsckaBSpCworaBGKsD0g3sBAeVAaD/P0ha46F4Uwoi/a3updfVPhwFRl/XrfbleOVyXAH4zaqosUyLzRv7kJyWmjol4vGF4iiHb9DnUmCFqfCOxfDmyqYFGcmnTv0gfOdOd1XLgVuUKMQwkKwayp5h5nnXyPUrzAYnl9E7XmoCrT4OX3ci+dgppbdmzQZ3Vxeyu8WBk0Rrw8OixFAaiOmhQTS/jNsQdAfViCIuX4jYLt1KYPRX1VAZnJce6DupuLKlk8INrzT9xwRVo95OEw68v8d38Gw5H5X1xNa9uAyBk="
  bucket: "vertigosmoothieware"
  skip_cleanup: true
  region: ap-southeast-2
  local_dir: releases
  on:
    branch: "release/vertigo-1"
